### ISSUE TITLE
How can I Dynamic Ajax Wordcloud??

### ISSUE THREAD

**Issue by thaerlabs** [robinboehm/angular-d3-directives#2]

**Comment by robinboehm** [comment]
Hey @thaer249 ,

that are exactly your need?
You can load the words via $http or $resource.

The WorldCloud directive need a $watch that rerender the cloud an some changes...
I could implemented this when you need this? :)

Rob

**Comment by areijngoudt** [comment]
Hi Robin,
I also need to create dynamic wordclouds. I have the ajax call in place and would like to bind the result from the rest service (a json array) to the wordcloud. I'm fairly new to Angular, so could you please help me with that?
Best regards, Ad

**Comment by areijngoudt** [comment]
Fixed it. This is the patch (from line 9512):
      link: function postLink(scope, element, attrs) {
          // BEGIN PATCH Ad 2013-11-13
          scope.$watch('words', function (newValue, oldValue) {
              if (newValue) {
                  var rootElement = element[0];
                  $(rootElement).children('svg').remove();
                  cloudFactory(newValue);
              }
          });
          // END PATCH Ad 2013-11-13
          var width = 800;

**Comment by robinboehm** [comment]
+1
If you like,
write a test and create a PR :)
